/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practica1;
import io.javalin.Javalin;
import io.javalin.http.staticfiles.Location;
import org.jasypt.util.text.BasicTextEncryptor;
import practica1.Clases.*;
import practica1.Controladores.*;

import practica1.Servicios.ArticuloServicio;
import practica1.Servicios.BootstrapService;
import practica1.Servicios.ConexionService;
import practica1.Servicios.UsuarioServicio;

import org.jasypt.util.text.BasicTextEncryptor;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

public class App {
    private static String modoConexion = "";

    public static void main(String[] args) throws SQLException {
        if(args.length >= 1){
            modoConexion = args[0];
            System.out.println("Modo de Operacion: "+modoConexion);
        }

        //Iniciando la base de datos.
        if(modoConexion.isEmpty()) {
            BootstrapService.getInstancia().init();
        }

        Javalin app = Javalin.create(config -> {
            config.addStaticFiles("/public", Location.CLASSPATH);
        }).start(7000);

        // Rutas

        new UsuarioControlador(app).aplicarRutas();
        new ArticuloControlador(app).aplicarRutas();
        new ComentarioControlador(app).aplicarRutas();
        new EtiquetaControlador(app).aplicarRutas();
        new MensajeriaControlador(app).aplicarRutas();

        //Servicios
        UsuarioServicio.getInstancia().crear(new Usuario("admin", "Admin", "12345", true, true));
        UsuarioServicio.getInstancia().crear(new Usuario("rodolfo_author", "Rodolfo Autor", "12345", false, true));
        UsuarioServicio.getInstancia().crear(new Usuario("rodolfo_client", "Rodolfo Cliente", "12345", false, false));

        ConexionService.getInstancia().crearTabla();
    }

}
