/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practica1;
import io.javalin.Javalin;
import io.javalin.http.staticfiles.Location;
import practica1.Controladores.ArticuloControlador;
import practica1.Controladores.ComentarioControlador;
import practica1.Controladores.UsuarioControlador;

import practica1.Servicios.UsuarioServicio;

public class App {
    public static void main(String[] args) {
        Javalin app = Javalin.create().start(7070);

        // Rutas

        new UsuarioControlador(app).aplicarRutas();
        new ArticuloControlador(app).aplicarRutas();
        new ComentarioControlador(app).aplicarRutas();

        //Servicios
        UsuarioServicio.getInstancia().crearUsuario("admin", "Admin", "12345", true, true);
    }
}
